### ISSUE TITLE
Auto Builds?

### ISSUE THREAD

**Issue by Manouchehri** [AeonLucid/MagiskFrida#1]
I noticed AppVeyor is already set up, but auto builds for the latest Frida release aren’t happening. Latest Frida build is 12.2.25, and the last build for MagiskFrida is 12.2.5. 

I’m not too familiar with AppVeyor, but would it be possible to trigger new builds on every Frida release?

Thanks!

**Comment by AeonLucid** [comment]
That should be possible but something has to trigger the build. Appveyor can not run itself when Frida has a new release.

I could run an application online which monitors Frida releases, runs appveyor and deploys to github. Most likely will do that unless someone else has a better idea.

**Comment by Manouchehri** [comment]
The fork at https://github.com/ViRb3/magisk-frida already does this. =)
