### ISSUE TITLE
Update magisk module template

### ISSUE THREAD

**Issue by rithvikvibhu** [AeonLucid/MagiskFrida#5]
More info: https://topjohnwu.github.io/Magisk/guides.html

https://twitter.com/topjohnwu/status/1111540546550534144
>Q: Does it work on old Magisk Managers?
>A: No, v7.1.0+ is required for the app to recognize and properly download the new format

>Q: So can people using v17.0 use my modules?
>A: Technically yes, but the new format can only be dloaded with manager v7.1.0+, and the min supported Magisk for the app is v18.0. If you release a zip separately with proper module_installer.sh, then yes your zip can be used on v17.0

**Comment by AeonLucid** [comment]
Fixed.

**Comment by rithvikvibhu** [comment]
Thanks!
